config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => 'topics#index'

  resources :topics do
    resources :ailments
  end

  resources :ailments do
    resources :cures
  end

end

app/models/ailment.rb
class Ailment < ActiveRecord::Base
  belongs_to :topic
  has_many :cures

  validates :description, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cure.rb
class Cure < ActiveRecord::Base

  belongs_to :ailment

  validates :url, :presence => true
  validates :headline, :presence => true
  validates :therapy, :presence => true
  validates :author, :presence => true
  validates :book_title, :presence => true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :ailments

  validates :name, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, :presence => true

end

app/controllers/ailments_controller.rb
class AilmentsController < ApplicationController

  def show
    @ailment = Ailment.find(params[:id])
    @cures = @ailment.cures
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @ailment = @topic.ailments.new
    respond_to do |format|
      format.html { render :new }
      format.js
    end
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @ailment = @topic.ailments.new(ailment_params)
    if @ailment.save
      flash[:notice] = "Ailment successfully created!"
      redirect_to topic_path(@ailment.topic)
    else
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @ailment = Ailment.find(params[:id])
    respond_to do |format|
      format.html { render :edit }
      format.js
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @ailment = Ailment.find(params[:id])
    if @ailment.update(ailment_params)
      flash[:notice] = "Ailment successfully updated!"
      redirect_to topic_path(@ailment.topic)
    else
      render :edit
    end
  end

  def destroy
    @ailment= Ailment.find(params[:id])
    @ailment.destroy
    flash[:notice] = "Ailment successfully deleted!"
    redirect_to topic_path(@ailment.topic)
  end

private
  def ailment_params
    params.require(:ailment).permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cures_controller.rb
 class CuresController < ApplicationController

   def new
     @ailment = Ailment.find(params[:ailment_id])
     @cure = @ailment.cures.new
     respond_to do |format|
       format.html { render :new }
       format.js
     end
   end

   def create
     @ailment = Ailment.find(params[:ailment_id])
     @cure = @ailment.cures.new(cure_params)
     if @cure.save
       flash[:notice] = "Cure successfully created!"
       redirect_to ailment_path(@cure.ailment)
     else
       render :new
     end
   end

   def edit
     @ailment = Ailment.find(params[:ailment_id])
     @cure = Cure.find(params[:id])
     respond_to do |format|
       format.html { render :edit }
       format.js
     end
   end

   def update
     @ailment = Ailment.find(params[:ailment_id])
     @cure = Cure.find(params[:id])
     if @cure.update(cure_params)
       flash[:notice] = "Cure successfully updated!"
       redirect_to ailment_path(@cure.ailment)
     else
       render :edit
     end
   end

   def destroy
     @cure = Cure.find(params[:id])
     @cure.destroy
     flash[:notice] = "Cure successfully deleted"
     redirect_to ailment_path(@cure.ailment)
   end

private
  def cure_params
    params.require(:cure).permit(:url, :headline, :therapy, :author, :book_title, :book_cover, :ailment_id)
  end

 end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
    respond_to do |format|
      format.html { render :new }
      format.js
    end
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      flash[:notice] = "Topic successfully added!"
      redirect_to topics_path
    else
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    respond_to do |format|
      format.html { render :edit }
      format.js
    end
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:notice] = "Topic successfully updated!"
      redirect_to topics_path
    else
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    flash[:notice] = "Topic successfully deleted!"
    redirect_to topics_path
  end

private
  def topic_params
    params.require(:topic).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
  end

  def show
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ailments/_form.html.erb
<%= render( 'layouts/errors', :object => @ailment ) %>

<%= form_for [@topic, @ailment], remote: true do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <p><%= f.submit %></p>
<% end %>

app/views/ailments/edit.html.erb
<% content_for(:title, "Update Ailment | Bibliotherapy") %>

<h1>Update Ailment</h1>

<%= render 'form' %>

app/views/ailments/edit.js.erb
$('#edit_ailment_js').hide().after('<%= j render("form") %>')

app/views/ailments/new.html.erb
<% content_for(:title, "New Ailment | Bibliotherapy") %>

<h1>New ailment for <%= @topic.name %></h1>

<%= render 'form' %>

app/views/ailments/new.js.erb
$('#new_ailment_js').hide().after('<%= j render("form") %>')

app/views/ailments/show.html.erb
<% content_for(:title, "Ailment | Bibliotherapy") %>

<h2><%= @ailment.description %></h2>

<p><%= link_to "Add a Bibliographic Cure", new_ailment_cure_path(@ailment), id: "new_cure_js", remote: true  %></p>

<% if @ailment.cures.any? %>

  <h4>Here are the bibliographic cures for this ailment: </h4>

  <ul>
    <% @ailment.cures.each do |cure| %>
      <li>Headline: <%= cure.headline %></li>
      <li>Therapy: <%= cure.therapy %></li>
      <li>Author: <%= cure.author %></li>
      <li>Book Title: <%= link_to cure.book_title, cure.url %></li>
      <li class="book-cover">Book Cover: <%= image_tag cure.book_cover %></li>
      <li><%= link_to "Edit", edit_ailment_cure_path(@ailment, cure), id: "edit_cure_js", remote: true %></li>
      <li><%= link_to "Delete", ailment_cure_path(@ailment, cure), :data => {:confirm => "Are you sure?", :method => "delete" }%></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no cures yet</p>
<% end %>

app/views/cures/_form.html.erb
<%= render( 'layouts/errors', :object => @cure ) %>

<%= form_for [@ailment, @cure], remote: true do |f| %>
  <%= f.label :headline %>
  <%= f.text_field :headline %>
  <%= f.label :therapy %>
  <%= f.text_field :therapy %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :book_title %>
  <%= f.text_field :book_title %>
  <%= f.label :book_cover %>
  <%= f.text_field :book_cover %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <p><%= f.submit %></p>
<% end %>

app/views/cures/edit.html.erb
<% content_for(:title, "Update Cure | Bibliotherapy") %>

<h2>Update Cure</h2>

<%= render 'form' %>

app/views/cures/edit.js.erb
$('#edit_cure_js').hide().after('<%= j render("form") %>')

app/views/cures/new.html.erb
<% content_for(:title, "New Cure | Bibliotherapy") %>

<h1>New cure for <%= @ailment.description %></h1>

<%= render 'form' %>

app/views/cures/new.js.erb
$('#new_cure_js').hide().after('<%= j render("form") %>')

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <% if user_signed_in? %>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></li>
            <% else %>
              <li><%= link_to "Sign In", user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/topics/_form.html.erb
<%= render "layouts/errors", :object => @topic %>

<%= form_for @topic, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<% content_for(:title, "Edit Topic | Bibliotherapy") %>

<h2>Edit topic</h2>

<%= render "form" %>

app/views/topics/edit.js.erb
$('#edit_topic_js').hide().after('<%= j render("form") %>')

app/views/topics/index.html.erb
<% content_for(:title, "Topics | Bibliotherapy") %>

<div class="row">
  <div class="logo">
    <h1>BIBLIOTHERAPY</h1>
  </div>
  <div class="quote">
    <p>
      <strong>bibliotherapy</strong> <i>noun</i> <br>
      : the prescribing of fiction for life's ailments <br>
      &mdash;Berthoud and Elderkin, 2013
    </p>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2>Topics</h2>
    <ul>
      <% @topics.each do |topic| %>
        <li><%= link_to topic.name, topic_path(topic) %></li>
      <% end %>
    </ul>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <%= link_to "New Topic", new_topic_path, :class => "btn btn-default btn-lg", id: "new_topic_js", remote: true %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- Begin MailChimp Signup Form -->
    <div id="mc_embed_signup">
    <form action="//epicodus.us14.list-manage.com/subscribe/post?u=3a05f993eacab5f8c4d63133f&amp;id=5170601140" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <div id="mc_embed_signup_scroll">
    	<h2>Subscribe to our mailing list</h2>
    <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
    <div class="mc-field-group">
    	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
    </label>
    	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
    </div>
    <div class="mc-field-group">
    	<label for="mce-FNAME">First Name </label>
    	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
    </div>
    <div class="mc-field-group">
    	<label for="mce-LNAME">Last Name </label>
    	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
    </div>
    	<div id="mce-responses" class="clear">
    		<div class="response" id="mce-error-response" style="display:none"></div>
    		<div class="response" id="mce-success-response" style="display:none"></div>
    	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_3a05f993eacab5f8c4d63133f_5170601140" tabindex="-1" value=""></div>
        <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
        </div>
    </form>
    </div>
    <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
    <!--End mc_embed_signup-->
  </div>
</div>

app/views/topics/new.html.erb
<% content_for(:title, "New Topic | Bibliotherapy") %>

<h2>New Topic</h2>

<%= render "form" %>

app/views/topics/new.js.erb
$('#new_topic_js').hide().after('<%= j render("form") %>')

app/views/topics/show.html.erb
<% content_for(:title, "Topic | Bibliotherapy") %>

<h2><%= @topic.name %></h2>

<p><%= link_to "Add an Ailment", new_topic_ailment_path(@topic), id: "new_ailment_js", remote: true %></p>

<% if @topic.ailments.any? %>

  <h4>Here are the ailments for this topic</h4>

  <ul>
    <% @topic.ailments.each do |ailment| %>
      <li>
        <%= link_to ailment.description, topic_ailment_path(@topic, ailment) %> |
        <%= link_to "Edit", edit_topic_ailment_path(@topic, ailment), id: "edit_ailment_js", remote: true %> |
        <%= link_to "Delete", topic_ailment_path(@topic, ailment),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
      <% end %>
  </ul>
<% else %>
  <p>There are no ailments yet!</p>
<% end %>

<hr>

<p><%= link_to "Update Topic", edit_topic_path(@topic), id: "edit_topic_js", remote: true %></p>
<p><%= link_to "Delete Topic", topic_path(@topic),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<p><%= link_to "Return to topics", topics_path %></p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>